credentials:
  usernames:
    testuser@example.com:
      email: testuser@example.com
      name: Test User
      password: "$2b$12$zvMv8.XUZ3Vm8Nz4lgqQJeHxi.lDmyYyQF0YBRhx5RhvxyjKSMmGy"  # password: test1234

cookie:
  expiry_days: 1
  key: secret_signature_key
  name: invoice_auth

preauthorized:
  emails:
    - testuser@example.com
