credentials:
  usernames:
    testuser@example.com:
      email: testuser@example.com
      name: Test User
      password: "$2b$12$5vt2v1QVy2K/.yeHY66NL.X77DYbMJaT.UsdXcJHzPYcvZo.z/icu"  # password: test1234

cookie:
  expiry_days: 1
  key: secret_signature_key
  name: invoice_auth

preauthorized:
  emails:
    - testuser@example.com
