credentials:
  usernames:
    praveen@tbhg.com:
      email: praveen@tbhg.com
      name: Praveen
      password: "$2b$12$eWzjXAZb75GHkq8ZoMQ0JOzxBTPCiIt8T8AxZxnelb6yq1yM80Ydu"

cookie:
  expiry_days: 1
  key: secret_signature_key
  name: invoice_auth

preauthorized:
  emails:
